### ISSUE TITLE
having trouble getting output from convolutional net

### ISSUE THREAD

**Issue by kylemcdonald** [benanne/Lasagne#181]
i trained a net with lasagne and now i want to start seeing how it performs empirically. to make sure i understand how to do this, i modified `mnist.py` to change 

```python
    l_in = lasagne.layers.InputLayer(
        shape=(batch_size, input_dim),
    )
```

from `batch_size` to `None` and then i added these lines:

```python
    img = _load_data()[0][0][0]
    print(output_layer.get_output_shape())
    print(output_layer.get_output_shape_for(img))
    print(output_layer.get_output(input=img).eval())
```

after the net is done training. it greets me with:

```
(None, 10)
(0.0, 10)
[[  5.91881201e-03   9.08960355e-05   7.25033786e-03   2.75585596e-02
    9.01725434e-06   9.57459569e-01   3.04876594e-04   6.14409277e-04
    5.99711020e-05   7.33550813e-04]]
```

showing that the first digit in the training set is, indeed, a 5.

i tried something similar to the `mnist_conv*.py` examples but could not get similar behavior. i change `batch_size` to `None` again and add:

```python
    img = _load_data()[0][0][0].reshape(28, 28) # also tried it flat
    print(output_layer.get_output_shape())
    print(output_layer.get_output_shape_for(img))
    print(output_layer.get_output(input=img).eval())
```

this prints an error instead. any advice?

```
(None, 10)
(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.], dtype=float32), 10)
Traceback (most recent call last):
  File "mnist_conv.py", line 141, in <module>
    main()
  File "mnist_conv.py", line 135, in main
    print(output_layer.get_output(input=img).eval())
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 128, in get_output
    layer_input = self.input_layer.get_output(input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/base.py", line 129, in get_output
    return self.get_output_for(layer_input, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/conv.py", line 186, in get_output_for
    border_mode=self.border_mode)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 151, in conv2d
    return op(input, filters)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 622, in make_node
    (inputs, _inputs.ndim))
TypeError: ConvOp (make_node) requires input be a 4D tensor; received "TensorConstant{[[ 0.     ..        ]]}" (2 dims)
```

**Comment by benanne** [comment]
Although the input shape can contain `None`, you should always pass a tensor of the correct dimensionality to `get_output()`. So you should always pass a 2D tensor (i.e. a matrix) to the first network. As far as I can tell, you are passing a vector, so this is not supposed to work (but apparently it does something sensible - don't rely on this though). To generate predictions for a single image, you should pass it a matrix of shape `(1, 784)` (the batch size is 1). For the convnet, you should pass a 4D tensor with shape `(batch_size, input_channels, height, width)`, so `(1, 1, 28, 28)`, not `(28, 28)` as you are doing.

There is another mistake in your code: `output_layer.get_output_shape_for(img)` does not make sense, the `get_output_shape_for()` method expects a shape tuple as its input, not a vector or matrix representing an input. So it should actually be `get_output_shape_for(img.shape)`. But that wouldn't work correctly either because the input shape should be a tuple with two values (i.e. representing a matrix), not 1 value (representing a vector).

By the way, please post questions like this on the mailing list: https://groups.google.com/forum/#!forum/lasagne-users
The GitHub issues are for development and bug reports. I will close this issue, if you wish to discuss this further we can do that on the mailing list. Thanks!

**Comment by kylemcdonald** [comment]
thanks so much! i was having trouble telling if this was a library bug or my mistake (because the 1d vector worked). but now i can see i was really just making a very simple error. i'll post any other questions to the mailing list unless i really have something to contribute :) thanks again!
